### ISSUE TITLE
Module not found: Error: Can't resolve 'ngx-speech/speech.service'

### ISSUE THREAD

**Issue by rahulbabu007** [onna/ngx-speech#1]
Get the error Module not found: Error: Can't resolve 'ngx-speech/speech.service' when I try to build the app. Installed using npm and can see ngx-speech under node_modules. But still this issue props up.

**Comment by Alexnapoles** [comment]
import { SpeechService } from 'ngx-speech/speech.service'; Thank me later <3

**Comment by rahulbabu007** [comment]
I tried this already but still get the error.

**Comment by ebrehault** [comment]
Ooops, seems like the dist packaging is wrong/.

You should be able to write:

```
import { SpeechModule, SpeechService } from 'ngx-speech';
```

I'll fix that ASAP.

**Comment by ebrehault** [comment]
Should be fixed now in 0.0.4

**Comment by sbourouis** [comment]
Hello @ebrehault, could you publish 0.0.4 to npm, please?

**Comment by ebrehault** [comment]
Oh sorry, my publish command failed yesterday and I did not realized.
Fixed.

**Comment by sbourouis** [comment]
Thank you !
